# Generated by Django 3.1.1 on 2020-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='word',
            name='partsOfSpeech',
            field=models.CharField(default='', max_length=25),
        ),
    ]
